POST http://localhost:8080/user/register HTTP/1.1
Content-Type: application/json

{
  "firstName":"Arham",
  "lastName": "Malik",
  "age":23,
  "email":"arham@gmail.com",
  "password":"arham",
  "bloodType":"A"
}



###
POST http://localhost:8080/user/login HTTP/1.1
Content-Type: application/json

{

  "email":"aan@gmail.com",
  "password":"aan"

}

###
GET http://localhost:8080/user/donor HTTP/1.1

###
POST http://localhost:8080/user/donor HTTP/1.1
Content-Type: application/json

{

  "bloodType":"O"
  

}